---
- name: Hello World!
  hosts: all
#  user: soichiro
  tasks:
 
# vmstat check
   - name: Check "vmstat -t 1 2" as SERVER RESOUCE
     shell: echo vmstat 1 10 | while read line; do  echo  `date` $line  ; done
     ignore_errors: yes
 
# Disk Size check
   - name: Check "df -h" as DISK SIZE
     shell: echo df -h
     ignore_errors: yes
 
# Memory Size check
   - name: Check "free -m" as Memory SIZE
     shell: echo free -m
     ignore_errors: yes
